version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - laravel
        command: >
            bash -c "
            composer install &&
            php artisan key:generate &&
            php artisan migrate --seed &&
            php-fpm"

    web:
        image: nginx:alpine
        container_name: laravel_web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: burh_db
            MYSQL_USER: burh_user
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        networks:
            - laravel
        volumes:
            - dbdata:/var/lib/mysql

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
